services:

# Web Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    ports:
      - "9001:80"
    depends_on:
     - db_mysql
    networks:
     - take_heli

  php:
    build: docker/php
    container_name: php
    working_dir: /var/www/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www
    networks:
      - take_heli

# Mysql Service
  db_mysql:
    container_name: db_mysql
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: Cartel
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - take_heli

  # Rabbitmq Service
#  rabbitmq:
#    image: rabbitmq:3.10.7-management
#    hostname: rabbitmq
#    restart: unless-stopped
#    environment:
#      - RABBITMQ_DEFAULT_USER=rmuser
#      - RABBITMQ_DEFAULT_PASS=rmpassword
#      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
#    volumes:
#      - ./docker/rabbitmq:/var/lib/rabbitmq
#    ports:
#      - 5672:5672
#      - 15672:15672
#    networks:
#      - take_heli

# PhpMyAdmin Service
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db_mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
    depends_on:
      - db_mysql
    networks:
      - take_heli

networks:
  take_heli:
#    external: true
    driver: bridge

volumes:
  postgres:
